### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by kbergha** [Dolphiq/craft3-jsonclient#2]
die() is not the best option if the URL is missing.
Also, there is no error handlig (or logging) if the request fails.

Do you want some help with this?

**Comment by johanzandstra** [comment]
@kbergha please feel free to add a pull request to the branch! thanks!

**Comment by kbergha** [comment]
This was fixed when you merged PR #1, commit: 893f895c897dd9cd8283289c2c813dad80cc6ba2
