### ISSUE TITLE
PHP Compile error on command line after installing plugin

### ISSUE THREAD

**Issue by kbergha** [Dolphiq/craft3-jsonclient#3]
After installing this plugin, the craft command line no longer works.

Craft 3 RC12
PHP 7.2
Running on a Homestead VM

Reproduce:
Install plugin
Try to run ./craft help on the command line.

Result:

vagrant@magasin:~/code$ ./craft help
PHP Compile Error 'yii\base\ErrorException' with message 'Cannot use craft\base\Object as Object because 'Object' is a special class name'

in /home/vagrant/code/vendor/dolphiq/jsonclient/src/JsonClientPlugin.php:21

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}

**Comment by xuanvan229** [comment]
Remove `use craft\base\Object`
it works for me

**Comment by kbergha** [comment]
Yep, I've fixed this and a few other issues in my pull request: #1

**Comment by colinwilson** [comment]
Hey @johanzandstra, any plans on merging @kbergha's [pull request](https://github.com/Dolphiq/craft3-jsonclient/pull/1) soon?

**Comment by Luuc15** [comment]
Fixed #6
