### ISSUE TITLE
PHP 7.2 incompatibility due to "Special class name" conflict.

### ISSUE THREAD

**Issue by monachilada** [Dolphiq/craft3-jsonclient#5]
It seems PHP 7.2 reserves the word `Object` as a "special class name". This means the plugin throws an error in the `JsonClientPlugin.php` file due to line 20:

`
use craft\base\Object;
`

As this seems to be a reference to a core **Craft** class, this may require core updates to fix, but I thought it still worth bringing to your attention.

Full screenshot of error message:

![screen shot 2018-08-02 at 10 27 38](https://user-images.githubusercontent.com/613183/43572039-c18b056c-963e-11e8-9ffc-89fd6bdb2513.png)

**Comment by angrybrad** [comment]
Craft itself doesn't have a `craft\base\Object` class and as far as I can tell, it never has, so not sure what that line is referencing.

**Comment by monachilada** [comment]
Strange. I've simply removed it and from what I can tell there are no adverse effects. I've filed a pull request in the hopes it can be resolved.

**Comment by JayBox325** [comment]
I'm getting this when I push it up to my staging site after setting this plugin up locally. Hopefully this gets included.

**Comment by Luuc15** [comment]
Should be fixed now :)

**Comment by monachilada** [comment]
@Luuc15 Thanks so much. I think the version number in `composer.json` will need to be bumped to trigger update notifications?
